[package]
name = "simd_learn"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "*"

[dev-dependencies]
criterion = { version = "*", features = ["html_reports"] }

[[bench]]
name = "simple"
harness = false
